export const adminDict = {
  sidebar: {
    title: 'وان تاير',
    panel: 'لوحة التحكم',
    overview: 'لوحة التحكم',
    requests: 'طلبات الخدمة',
    messages: 'الرسائل الواردة',
    blog: 'المدونة',
    offers: 'العروض',
    media: 'مكتبة الوسائط',
    brands: 'العلامات التجارية',
    services: 'الخدمات',
    testimonials: 'آراء العملاء',
    settings: 'الإعدادات',
    signOut: 'تسجيل الخروج',
  },
  header: {
    searchPlaceholder: 'البحث عن الطلبات، مقالات المدونة...',
    profileSettings: 'إعدادات الملف الشخصي',
    accountPreferences: 'تفضيلات الحساب',
    logout: 'تسجيل الخروج',
  },
  overview: {
    title: 'لوحة التحكم الرئيسية',
    subtitle: 'مرحباً بك في لوحة تحكم One Tire. إليك حالة العمليات الحالية.',
    requestsCard: 'طلبات الخدمة',
    requestsDesc: 'إجمالي استفسارات الخدمة المتنقلة',
    blogCard: 'مقالات المدونة',
    blogDesc: 'المقالات والمنشورات المنشورة',
    mediaCard: 'مكتبة الوسائط',
    mediaDesc: 'الصور والأصول المرفوعة',
    vansCard: 'الفنيين النشطين',
    vansDesc: 'سيارات الخدمة المتنقلة على الطريق',
    recentRequests: 'طلبات الخدمة الأخيرة',
    recentRequestsDesc: 'أحدث حجوزات الخدمة المتنقلة على الطريق.',
    noRequests: 'لا توجد طلبات حديثة.',
    fleetPerformance: 'أداء الأسطول',
    fleetDesc: 'مؤشرات كفاءة التوزيع والوصول',
    avgResponse: 'متوسط وقت الاستجابة',
    avgResponseVal: '22 دقيقة',
    completionRate: 'معدل إتمام المهام',
    completionRateVal: '96%',
  },
  blog: {
    title: 'إدارة المدونة',
    subtitle: 'إنشاء وتعديل ونشر المقالات لـ One Tire.',
    writeBtn: 'كتابة مقال جديد',
    listTitle: 'قائمة المقالات',
    listDesc: 'إدارة مسودات ومقالات المدونة المنشورة.',
    noPosts: 'لم يتم العثور على مقالات. اضغط على "كتابة مقال جديد" لإضافة مقالك الأول!',
    titleCol: 'العنوان',
    slugCol: 'الرابط الفريد (Slug)',
    dateCol: 'تاريخ الإنشاء',
    statusCol: 'الحالة',
    actionsCol: 'الإجراءات',
    editBtn: 'تعديل',
    viewBtn: 'عرض على الموقع',
    createTitle: 'كتابة مقال جديد',
    createSubtitle: 'اكتب مقالاً جديداً وضبط إعدادات الـ SEO.',
    editTitle: 'تعديل المقال',
    editSubtitle: 'تعديل وتحديث تفاصيل المقال الحالي.',
    formBodyTitle: 'محتوى المقال',
    formBodyDesc: 'المحتوى الرئيسي للمقال.',
    titleLabel: 'عنوان المقال',
    slugLabel: 'الرابط الفريد (Slug)',
    contentLabel: 'محتوى المقال (Markdown أو HTML)',
    coverLabel: 'رابط الصورة البارزة (من مكتبة الوسائط)',
    statusLabel: 'حالة النشر',
    metaTitleLabel: 'عنوان الميتا (Meta Title)',
    metaDescLabel: 'وصف الميتا (Meta Description)',
    saveDraft: 'حفظ كمسودة',
    publish: 'نشر المقال',
    cancel: 'إلغاء',
    saving: 'جاري الحفظ...',
  },
  offers: {
    title: 'إدارة العروض',
    subtitle: 'إنشاء وتعديل ونشر العروض الترويجية والخصومات الحصرية.',
    createBtn: 'إنشاء عرض جديد',
    listTitle: 'قائمة العروض والخصومات',
    listDesc: 'إدارة العروض الترويجية النشطة والمسودات.',
    noOffers: 'لا توجد عروض حالياً. اضغط على "إنشاء عرض جديد" لإضافة عرضك الأول!',
    editTitle: 'تعديل العرض',
    createTitle: 'إنشاء عرض جديد',
    createSubtitle: 'تفاصيل العرض الترويجي والخصومات.',
    detailsCard: 'تفاصيل العرض',
    settingsCard: 'الإعدادات والصور',
    coverLabel: 'الصورة البارزة للعرض',
  },
  media: {
    title: 'مكتبة الوسائط والملفات',
    subtitle: 'رفع وإدارة الصور والملفات. يمكنك اختيارها مباشرة في النماذج دون الحاجة لنسخ الروابط.',
    uploadBtn: 'رفع صورة',
    uploading: 'جاري الرفع...',
    noMedia: 'لا توجد صور مرفوعة بعد. اسحب وأفلت الصور هنا أو اضغط للرفع.',
    dragDropText: 'اسحب وأفلت الصور هنا أو اضغط للتصفح والرفع',
    copyUrl: 'نسخ الرابط',
    deleteBtn: 'حذف',
    confirmDelete: 'هل أنت متأكد من رغبتك في حذف هذه الصورة نهائياً؟',
    copiedMsg: 'تم نسخ رابط الصورة بنجاح!',
    usedIn: 'مستخدمة في:',
  },
  settings: {
    title: 'إعدادات الموقع والمحتوى',
    subtitle: 'التحكم في النصوص العامة والترجمات والصور الرئيسية للموقع.',
    globalMedia: 'الوسائط والصور العامة',
    globalMediaDesc: 'الصور الرئيسية المستخدمة في أقسام الموقع المختلفة. انقر على الحقل لاختيار الصورة مباشرة من مكتبة الوسائط.',
    heroBgLabel: 'صورة خلفية الهيرو (الرئيسية)',
    whyImgLabel: 'صورة قسم "لماذا تختارنا"',
    ctaImgLabel: 'صورة قسم "اتصل بنا / الدعوة للإجراء"',
    seoCard: 'تحسين محركات البحث (SEO & Meta)',
    seoDesc: 'الإعدادات الافتراضية والكلمات المفتاحية لموقعك للظهور في محركات البحث.',
    seoTitleAr: 'عنوان الموقع الافتراضي (بالعربية)',
    seoTitleEn: 'عنوان الموقع الافتراضي (بالإنجليزية)',
    seoDescAr: 'وصف الموقع الافتراضي (بالعربية)',
    seoDescEn: 'وصف الموقع الافتراضي (بالإنجليزية)',
    seoKeywords: 'الكلمات المفتاحية (Keywords - مفصولة بفاصلة)',
    ogImgLabel: 'صورة المشاركة الافتراضية (OG Image)',
    heroCard: 'قسم الهيرو الرئيسي',
    title1Ar: 'العنوان الأول (عربي)',
    title1En: 'العنوان الأول (إنجليزي)',
    title2Ar: 'العنوان الثاني - المميز (عربي)',
    title2En: 'العنوان الثاني - المميز (إنجليزي)',
    descAr: 'الوصف الرئيسي (عربي)',
    descEn: 'الوصف الرئيسي (إنجليزي)',
    whyCard: 'قسم "لماذا تختارنا"',
    whyTitleAr: 'العنوان (عربي)',
    whyTitleEn: 'العنوان (إنجليزي)',
    whyDescAr: 'الوصف (عربي)',
    whyDescEn: 'الوصف (إنجليزي)',
    servicesCard: 'قسم الخدمات',
    covCard: 'قسم مناطق التغطية',
    contactCard: 'قسم اتصل بنا والـ CTA',
    saveBtn: 'حفظ جميع التغييرات',
  },
  services: {
    title: 'إدارة الخدمات',
    subtitle: 'إضافة وتعديل الخدمات المتنقلة المتاحة على الموقع.',
    addBtn: 'إضافة خدمة جديدة',
    listTitle: 'كل الخدمات',
    noServices: 'لا توجد خدمات متاحة. اضغط على "إضافة خدمة" للبدء.',
    newService: 'خدمة جديدة',
    editService: 'تعديل الخدمة',
    formTitle: 'عنوان الخدمة',
    formDesc: 'وصف الخدمة بالتفصيل',
    formIcon: 'اسم الأيقونة (من Lucide)',
    formImage: 'صورة الخدمة (من مكتبة الوسائط)',
    formOrder: 'ترتيب العرض',
    formVisible: 'ظاهرة على الموقع',
    saveBtn: 'حفظ الخدمة',
    deleteBtn: 'حذف الخدمة',
  },
  brands: {
    title: 'إدارة العلامات التجارية (الماركات)',
    subtitle: 'إدارة شعارات ماركات الإطارات المعروضة في الصفحة الرئيسية.',
    addBtn: 'إضافة ماركة جديدة',
    listTitle: 'كل العلامات التجارية',
    noBrands: 'لا توجد علامات تجارية. اضغط على "إضافة ماركة" للبدء.',
    newBrand: 'ماركة جديدة',
    editBrand: 'تعديل الماركة',
    formName: 'اسم الماركة',
    formLogo: 'شعار الماركة (من مكتبة الوسائط)',
    formOrder: 'ترتيب العرض',
    formVisible: 'ظاهرة على الموقع',
    saveBtn: 'حفظ الماركة',
    deleteBtn: 'حذف الماركة',
  },
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    statusDraft: 'مسودة',
    statusPublished: 'منشور',
    statusPending: 'قيد الانتظار',
    statusAssigned: 'تم التعيين',
    statusCompleted: 'مكتمل',
    visible: 'مرئي',
    hidden: 'مخفي',
  }
};
